# Generated by Django 4.2.4 on 2023-10-31 07:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="FormSavedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="app.form"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormFields",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("ti", "Text Input"),
                            ("no", "Number Input"),
                            ("em", "Email"),
                            ("ph", "Phone Number"),
                            ("dd", "Drop Down"),
                            ("ss", "Single Select"),
                            ("ms", "Multi Select"),
                            ("ta", "Text Area"),
                        ],
                        max_length=2,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("placeholder", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=True)),
                ("min_length", models.PositiveIntegerField(default=0)),
                ("max_length", models.PositiveIntegerField(default=0)),
                ("choices", models.TextField(blank=True, null=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.form"
                    ),
                ),
            ],
        ),
    ]
