# Generated by Django 4.2.4 on 2023-08-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormFields",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("ti", "Text Input"),
                            ("no", "Number Input"),
                            ("em", "Email"),
                            ("ph", "Phone Number"),
                            ("dd", "Drop Down"),
                            ("ss", "Single Select"),
                            ("ms", "Multi Select"),
                            ("ta", "Text Area"),
                        ],
                        max_length=2,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("placeholder", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=True)),
                ("min_length", models.PositiveIntegerField(default=0)),
                ("max_length", models.PositiveIntegerField(default=0)),
                ("form", models.ManyToManyField(to="app.form")),
            ],
        ),
    ]
