# Generated by Django 4.2.4 on 2023-10-29 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_formfields"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormSavedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="app.form"
                    ),
                ),
            ],
        ),
    ]
